require 'i18n'
require_relative '../lib/modules/data_base.rb'
require_relative '../lib/modules/statistics.rb'
require_relative '../lib/modules/rules.rb'
require_relative '../lib/modules/validator.rb'
require_relative '../lib/entities/respondent.rb'
require_relative '../lib/entities/player.rb'
require_relative '../lib/entities/test.rb'
require_relative '../lib/entities/game.rb'
require_relative '../lib/entities/console.rb'
I18n.load_path << Dir[File.expand_path('./lib/messages/en.yml')]
